# =========================================================================
# STANDARD GLOBAL IMPORTS & CONFIGURATIONS (utils/config.py)
# =========================================================================
import os

import streamlit as st
from dotenv import load_dotenv

# Clean imports from the modern SDK
from supabase import ClientOptions, create_client

from utils.logging_config import get_logger

logger = get_logger(__name__)

# 1. Look for and load local hidden .env file
load_dotenv()

def get_secret(key: str, default=None):
    if hasattr(st, "secrets") and st.secrets is not None:
        try:
            secret_value = st.secrets.get(key)
            if secret_value:
                return secret_value
        except Exception:
            logger.debug("st.secrets lookup for %r failed; falling back to env", key, exc_info=True)
    return os.getenv(key, default)

# --- GLOBAL CREDENTIALS & SCM CONSTANTS ---
GEMINI_API_KEY = get_secret("GEMINI_API_KEY")
SUPABASE_URL = get_secret("SUPABASE_URL")
SUPABASE_ANON_KEY = get_secret("SUPABASE_ANON_KEY")
SUPABASE_SERVICE_ROLE_KEY = get_secret("SUPABASE_SERVICE_ROLE_KEY")

SUPABASE_ENABLED = bool(SUPABASE_URL and SUPABASE_ANON_KEY)
SUPABASE_SERVICE_ENABLED = bool(SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY)

# Supabase clients are built lazily on first use rather than at import time, so
# importing this module — and therefore the whole app — never depends on
# credentials being present and stays cheap to import/test. Each client is
# created once and cached.
_supabase_client = None
_supabase_service_client = None

# The anon client is a module-level singleton shared by every browser session, and
# utils.auth.get_supabase_client() re-applies the caller's own access token on every
# use — the client is deliberately treated as holding no session of its own.
#
# auto_refresh_token (SDK default: True) breaks exactly that assumption. Saving a session
# arms a background timer thread that refreshes whatever session the client last stored.
# Supabase ROTATES the refresh token on every refresh and revokes the previous one —
# including the copy sitting in the user's browser cookie — while handing the replacement
# only to the client's own memory, where nothing ever reads it. So roughly an hour after
# login the cookie's token is silently dead, and the next browser reload cannot restore
# the session: the field user lands back on the login screen mid-shift.
#
# Refreshing is restore_session()'s job, and it passes the token explicitly.
# Pinned by tests/test_session_persistence.py::TestClientDoesNotRotateTokensBehindOurBack.
_CLIENT_OPTIONS = ClientOptions(auto_refresh_token=False)


def get_base_supabase_client():
    """Anon Supabase client, created once on first use. None if not configured."""
    global _supabase_client
    if not SUPABASE_ENABLED:
        return None
    if _supabase_client is None:
        _supabase_client = create_client(SUPABASE_URL, SUPABASE_ANON_KEY, options=_CLIENT_OPTIONS)
    return _supabase_client


def get_service_supabase_client():
    """Service-role Supabase client, created once on first use. None if not configured."""
    global _supabase_service_client
    if not SUPABASE_SERVICE_ENABLED:
        return None
    if _supabase_service_client is None:
        _supabase_service_client = create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)
    return _supabase_service_client
UPLOAD_DIR = "uploaded_field_sheets"

# --- LOCAL FALLBACK AUTHENTICATION CREDENTIAL SETTINGS ---
# Credentials must be supplied via secrets/env — never hardcoded. If neither
# ADMIN_PASSWORD_HASH nor ADMIN_PASSWORD is set, the local-admin fallback login
# is disabled and only Supabase authentication is available.
#
# Prefer ADMIN_PASSWORD_HASH — a PBKDF2-SHA256 digest ("pbkdf2_sha256$...")
# generated by scripts/hash_admin_password.py — so no plaintext admin password
# ever lives in secrets.toml/env. ADMIN_PASSWORD (plaintext) is still honoured
# for backward compatibility, but the hash takes precedence when both are set.
ADMIN_USERNAME = get_secret("ADMIN_USERNAME", "admin")
ADMIN_EMAIL = get_secret("ADMIN_EMAIL", "admin@localhost")
ADMIN_PASSWORD = get_secret("ADMIN_PASSWORD")
ADMIN_PASSWORD_HASH = get_secret("ADMIN_PASSWORD_HASH")

# Second gate in front of the admin bulk delete ("remove every entry in the project"),
# asked for on top of being a registered admin. Same PBKDF2 format as ADMIN_PASSWORD_HASH;
# generate one with scripts/hash_admin_passkey.py. There is deliberately no plaintext
# fallback and no default: if this is unset the bulk delete stays disabled, because the
# alternative — a wipe reachable by anyone who reaches the page — is worse than a feature
# that has to be configured before it works.
#
# It is a confirmation step, not the security boundary. Who may delete what is enforced by
# RLS (sql/add_ownership_delete_policies.sql); a registered admin holding their own JWT
# could delete through the API without ever seeing this prompt. What it buys is that a
# logged-in admin's unattended session, or a misclick, cannot empty the project.
ADMIN_DELETE_PASSKEY_HASH = get_secret("ADMIN_DELETE_PASSKEY_HASH")

# Ensure upload directory exists right away
if not os.path.exists(UPLOAD_DIR):
    os.makedirs(UPLOAD_DIR)

# --- SYSTEM STATE BOOTSTRAPPING ENGINE ---
def initialize_auth_state():
    defaults = {
        "authenticated": False,
        "auth_provider": "local",
        "auth_user_email": None,
        "auth_user_id": None,
        "auth_user_name": None,
        "remember_me": False,
        "login_time": None,
        "current_page": "dashboard",
        "gemini_chat_history": [],
        "captcha_attempts": 0,
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value
